[2017-09-18 23:11:23] request.INFO: Matched route "admin". {"route":"admin","route_parameters":{"_controller":"AppBundle\\Controller\\AdminController::indexAction","_route":"admin"},"request_uri":"http://guilder.local/admin","method":"GET"} []
[2017-09-18 23:11:23] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-18 23:11:23] security.DEBUG: User was reloaded from a user provider. {"username":"usuario1","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
[2017-09-18 23:11:23] security.DEBUG: Access denied, the user is neither anonymous, nor remember-me. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at C:\\xampp\\htdocs\\Proyecto\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\AccessListener.php:70)"} []
[2017-09-18 23:11:23] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: "Access Denied." at C:\xampp\htdocs\Proyecto\vendor\symfony\symfony\src\Symfony\Component\Security\Http\Firewall\ExceptionListener.php line 123 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): Access Denied. at C:\\xampp\\htdocs\\Proyecto\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\ExceptionListener.php:123, Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at C:\\xampp\\htdocs\\Proyecto\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\AccessListener.php:70)"} []
[2017-09-18 23:11:23] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-18 23:12:10] request.INFO: Matched route "admin". {"route":"admin","route_parameters":{"_controller":"AppBundle\\Controller\\AdminController::indexAction","_route":"admin"},"request_uri":"http://guilder.local/admin","method":"GET"} []
[2017-09-18 23:12:10] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-18 23:12:10] security.DEBUG: User was reloaded from a user provider. {"username":"admin1","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
[2017-09-18 23:12:10] security.DEBUG: Access denied, the user is neither anonymous, nor remember-me. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at C:\\xampp\\htdocs\\Proyecto\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\AccessListener.php:70)"} []
[2017-09-18 23:12:10] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: "Access Denied." at C:\xampp\htdocs\Proyecto\vendor\symfony\symfony\src\Symfony\Component\Security\Http\Firewall\ExceptionListener.php line 123 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): Access Denied. at C:\\xampp\\htdocs\\Proyecto\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\ExceptionListener.php:123, Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at C:\\xampp\\htdocs\\Proyecto\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\AccessListener.php:70)"} []
[2017-09-18 23:12:10] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-18 23:12:41] request.INFO: Matched route "admin". {"route":"admin","route_parameters":{"_controller":"AppBundle\\Controller\\AdminController::indexAction","_route":"admin"},"request_uri":"http://guilder.local/admin","method":"GET"} []
[2017-09-18 23:12:41] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-18 23:12:41] security.DEBUG: User was reloaded from a user provider. {"username":"admin1","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
[2017-09-18 23:12:41] security.DEBUG: Access denied, the user is neither anonymous, nor remember-me. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at C:\\xampp\\htdocs\\Proyecto\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\AccessListener.php:70)"} []
[2017-09-18 23:12:41] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: "Access Denied." at C:\xampp\htdocs\Proyecto\vendor\symfony\symfony\src\Symfony\Component\Security\Http\Firewall\ExceptionListener.php line 123 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): Access Denied. at C:\\xampp\\htdocs\\Proyecto\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\ExceptionListener.php:123, Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at C:\\xampp\\htdocs\\Proyecto\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\AccessListener.php:70)"} []
[2017-09-18 23:12:41] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-18 23:14:38] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /crearusuario"" at C:\xampp\htdocs\Proyecto\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /crearusuario\" at C:\\xampp\\htdocs\\Proyecto\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\xampp\\htdocs\\Proyecto\\var\\cache\\prod\\appProdProjectContainerUrlMatcher.php:201)"} []
[2017-09-18 23:14:44] request.INFO: Matched route "crearUsuarios". {"route":"crearUsuarios","route_parameters":{"_controller":"AppBundle\\Controller\\DefaultController::registerAction","_route":"crearUsuarios"},"request_uri":"http://guilder.local/crearusuarios","method":"GET"} []
[2017-09-18 23:14:44] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-18 23:14:44] security.DEBUG: User was reloaded from a user provider. {"username":"admin1","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
[2017-09-18 23:14:45] request.CRITICAL: Uncaught PHP Exception Doctrine\DBAL\Exception\UniqueConstraintViolationException: "An exception occurred while executing 'INSERT INTO user (username, password, is_active, email, legajo, carrera_idcarrera, rol_idrol) VALUES (?, ?, ?, ?, ?, ?, ?)' with params ["usuario1", "$2y$13$y2vui3gmuaQTuntLHAhl4O5UZhy0ICG.oY1BJITXjH8uoDJxVCnXy", 1, null, null, null, 4]:  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'usuario1' for key 'UNIQ_2DA17977F85E0677'" at C:\xampp\htdocs\Proyecto\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php line 66 {"exception":"[object] (Doctrine\\DBAL\\Exception\\UniqueConstraintViolationException(code: 0): An exception occurred while executing 'INSERT INTO user (username, password, is_active, email, legajo, carrera_idcarrera, rol_idrol) VALUES (?, ?, ?, ?, ?, ?, ?)' with params [\"usuario1\", \"$2y$13$y2vui3gmuaQTuntLHAhl4O5UZhy0ICG.oY1BJITXjH8uoDJxVCnXy\", 1, null, null, null, 4]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'usuario1' for key 'UNIQ_2DA17977F85E0677' at C:\\xampp\\htdocs\\Proyecto\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php:66, Doctrine\\DBAL\\Driver\\PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'usuario1' for key 'UNIQ_2DA17977F85E0677' at C:\\xampp\\htdocs\\Proyecto\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:107, PDOException(code: 23000): SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'usuario1' for key 'UNIQ_2DA17977F85E0677' at C:\\xampp\\htdocs\\Proyecto\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\PDOStatement.php:105)"} []
[2017-09-18 23:14:45] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-19 00:51:40] request.INFO: Matched route "admin". {"route":"admin","route_parameters":{"_controller":"AppBundle\\Controller\\AdminController::indexAction","_route":"admin"},"request_uri":"http://guilder.local/admin","method":"GET"} []
[2017-09-19 00:51:40] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-19 00:51:41] security.DEBUG: User was reloaded from a user provider. {"username":"admin1","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
[2017-09-19 00:51:41] security.DEBUG: Access denied, the user is neither anonymous, nor remember-me. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at C:\\xampp\\htdocs\\Proyecto\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\AccessListener.php:70)"} []
[2017-09-19 00:51:41] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: "Access Denied." at C:\xampp\htdocs\Proyecto\vendor\symfony\symfony\src\Symfony\Component\Security\Http\Firewall\ExceptionListener.php line 123 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): Access Denied. at C:\\xampp\\htdocs\\Proyecto\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\ExceptionListener.php:123, Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at C:\\xampp\\htdocs\\Proyecto\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\AccessListener.php:70)"} []
[2017-09-19 00:51:41] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-19 00:51:43] request.INFO: Matched route "admin". {"route":"admin","route_parameters":{"_controller":"AppBundle\\Controller\\AdminController::indexAction","_route":"admin"},"request_uri":"http://guilder.local/admin","method":"GET"} []
[2017-09-19 00:51:43] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-19 00:51:43] security.DEBUG: User was reloaded from a user provider. {"username":"admin1","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
[2017-09-19 00:51:43] security.DEBUG: Access denied, the user is neither anonymous, nor remember-me. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at C:\\xampp\\htdocs\\Proyecto\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\AccessListener.php:70)"} []
[2017-09-19 00:51:43] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: "Access Denied." at C:\xampp\htdocs\Proyecto\vendor\symfony\symfony\src\Symfony\Component\Security\Http\Firewall\ExceptionListener.php line 123 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): Access Denied. at C:\\xampp\\htdocs\\Proyecto\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\ExceptionListener.php:123, Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at C:\\xampp\\htdocs\\Proyecto\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\AccessListener.php:70)"} []
[2017-09-19 00:51:43] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-19 00:51:44] request.INFO: Matched route "admin". {"route":"admin","route_parameters":{"_controller":"AppBundle\\Controller\\AdminController::indexAction","_route":"admin"},"request_uri":"http://guilder.local/admin","method":"GET"} []
[2017-09-19 00:51:44] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-19 00:51:44] security.DEBUG: User was reloaded from a user provider. {"username":"admin1","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
[2017-09-19 00:51:44] security.DEBUG: Access denied, the user is neither anonymous, nor remember-me. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at C:\\xampp\\htdocs\\Proyecto\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\AccessListener.php:70)"} []
[2017-09-19 00:51:44] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: "Access Denied." at C:\xampp\htdocs\Proyecto\vendor\symfony\symfony\src\Symfony\Component\Security\Http\Firewall\ExceptionListener.php line 123 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): Access Denied. at C:\\xampp\\htdocs\\Proyecto\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\ExceptionListener.php:123, Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at C:\\xampp\\htdocs\\Proyecto\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\AccessListener.php:70)"} []
[2017-09-19 00:51:44] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-19 00:53:12] request.INFO: Matched route "admin". {"route":"admin","route_parameters":{"_controller":"AppBundle\\Controller\\AdminController::indexAction","_route":"admin"},"request_uri":"http://guilder.local/admin","method":"GET"} []
[2017-09-19 00:53:12] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-19 00:53:13] security.DEBUG: User was reloaded from a user provider. {"username":"admin1","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
[2017-09-19 00:53:13] security.DEBUG: Access denied, the user is neither anonymous, nor remember-me. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at C:\\xampp\\htdocs\\Proyecto\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\AccessListener.php:70)"} []
[2017-09-19 00:53:13] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: "Access Denied." at C:\xampp\htdocs\Proyecto\vendor\symfony\symfony\src\Symfony\Component\Security\Http\Firewall\ExceptionListener.php line 123 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): Access Denied. at C:\\xampp\\htdocs\\Proyecto\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\ExceptionListener.php:123, Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at C:\\xampp\\htdocs\\Proyecto\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\AccessListener.php:70)"} []
[2017-09-19 00:53:13] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-19 00:53:51] request.INFO: Matched route "admin". {"route":"admin","route_parameters":{"_controller":"AppBundle\\Controller\\AdminController::indexAction","_route":"admin"},"request_uri":"http://guilder.local/admin","method":"GET"} []
[2017-09-19 00:53:51] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-19 00:53:51] security.DEBUG: User was reloaded from a user provider. {"username":"admin1","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
[2017-09-19 00:53:51] security.DEBUG: Access denied, the user is neither anonymous, nor remember-me. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at C:\\xampp\\htdocs\\Proyecto\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\AccessListener.php:70)"} []
[2017-09-19 00:53:51] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: "Access Denied." at C:\xampp\htdocs\Proyecto\vendor\symfony\symfony\src\Symfony\Component\Security\Http\Firewall\ExceptionListener.php line 123 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): Access Denied. at C:\\xampp\\htdocs\\Proyecto\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\ExceptionListener.php:123, Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at C:\\xampp\\htdocs\\Proyecto\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\AccessListener.php:70)"} []
[2017-09-19 00:53:51] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-19 00:53:53] request.INFO: Matched route "admin". {"route":"admin","route_parameters":{"_controller":"AppBundle\\Controller\\AdminController::indexAction","_route":"admin"},"request_uri":"http://guilder.local/admin","method":"GET"} []
[2017-09-19 00:53:53] security.DEBUG: Read existing security token from the session. {"key":"_security_main"} []
[2017-09-19 00:53:53] security.DEBUG: User was reloaded from a user provider. {"username":"admin1","provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider"} []
[2017-09-19 00:53:53] security.DEBUG: Access denied, the user is neither anonymous, nor remember-me. {"exception":"[object] (Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at C:\\xampp\\htdocs\\Proyecto\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\AccessListener.php:70)"} []
[2017-09-19 00:53:53] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException: "Access Denied." at C:\xampp\htdocs\Proyecto\vendor\symfony\symfony\src\Symfony\Component\Security\Http\Firewall\ExceptionListener.php line 123 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\AccessDeniedHttpException(code: 0): Access Denied. at C:\\xampp\\htdocs\\Proyecto\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\ExceptionListener.php:123, Symfony\\Component\\Security\\Core\\Exception\\AccessDeniedException(code: 403): Access Denied. at C:\\xampp\\htdocs\\Proyecto\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Http\\Firewall\\AccessListener.php:70)"} []
[2017-09-19 00:53:53] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2017-09-19 01:25:09] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /tokens"" at C:\xampp\htdocs\Proyecto\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /tokens\" at C:\\xampp\\htdocs\\Proyecto\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\xampp\\htdocs\\Proyecto\\var\\cache\\prod\\appProdProjectContainerUrlMatcher.php:201)"} []
[2017-09-19 01:25:23] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /usuarios"" at C:\xampp\htdocs\Proyecto\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /usuarios\" at C:\\xampp\\htdocs\\Proyecto\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\xampp\\htdocs\\Proyecto\\var\\cache\\prod\\appProdProjectContainerUrlMatcher.php:201)"} []
[2017-09-19 01:25:25] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /usuario"" at C:\xampp\htdocs\Proyecto\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /usuario\" at C:\\xampp\\htdocs\\Proyecto\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\xampp\\htdocs\\Proyecto\\var\\cache\\prod\\appProdProjectContainerUrlMatcher.php:201)"} []
[2017-09-19 03:46:08] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /excel"" at C:\xampp\htdocs\Proyecto\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /excel\" at C:\\xampp\\htdocs\\Proyecto\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\xampp\\htdocs\\Proyecto\\var\\cache\\prod\\appProdProjectContainerUrlMatcher.php:201)"} []
[2017-09-19 03:47:21] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /excel"" at C:\xampp\htdocs\Proyecto\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /excel\" at C:\\xampp\\htdocs\\Proyecto\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\xampp\\htdocs\\Proyecto\\var\\cache\\prod\\appProdProjectContainerUrlMatcher.php:201)"} []
[2017-09-19 03:54:56] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /excel"" at C:\xampp\htdocs\Proyecto\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /excel\" at C:\\xampp\\htdocs\\Proyecto\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\xampp\\htdocs\\Proyecto\\var\\cache\\prod\\appProdProjectContainerUrlMatcher.php:201)"} []
[2017-09-19 03:54:57] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /excel"" at C:\xampp\htdocs\Proyecto\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /excel\" at C:\\xampp\\htdocs\\Proyecto\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\xampp\\htdocs\\Proyecto\\var\\cache\\prod\\appProdProjectContainerUrlMatcher.php:201)"} []
[2017-09-19 04:00:33] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /excel"" at C:\xampp\htdocs\Proyecto\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /excel\" at C:\\xampp\\htdocs\\Proyecto\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\xampp\\htdocs\\Proyecto\\var\\cache\\prod\\appProdProjectContainerUrlMatcher.php:201)"} []
[2017-09-19 04:00:36] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /excel"" at C:\xampp\htdocs\Proyecto\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /excel\" at C:\\xampp\\htdocs\\Proyecto\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\xampp\\htdocs\\Proyecto\\var\\cache\\prod\\appProdProjectContainerUrlMatcher.php:201)"} []
[2017-09-19 04:52:09] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /excel"" at C:\xampp\htdocs\Proyecto\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /excel\" at C:\\xampp\\htdocs\\Proyecto\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\xampp\\htdocs\\Proyecto\\var\\cache\\prod\\appProdProjectContainerUrlMatcher.php:201)"} []
[2017-09-19 05:02:06] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /comision/"" at C:\xampp\htdocs\Proyecto\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /comision/\" at C:\\xampp\\htdocs\\Proyecto\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\xampp\\htdocs\\Proyecto\\var\\cache\\prod\\appProdProjectContainerUrlMatcher.php:201)"} []
[2017-09-25 01:57:15] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST /Controller/EncuestaController.php" (from "http://guilder.local/app_dev.php/modulo3")" at C:\xampp\htdocs\Proyecto\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /Controller/EncuestaController.php\" (from \"http://guilder.local/app_dev.php/modulo3\") at C:\\xampp\\htdocs\\Proyecto\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\xampp\\htdocs\\Proyecto\\var\\cache\\prod\\appProdProjectContainerUrlMatcher.php:201)"} []
[2017-09-25 01:58:15] request.INFO: Matched route "modulo1". {"route":"modulo1","route_parameters":{"_controller":"AppBundle\\Controller\\ModuloController::indexAction","_route":"modulo1"},"request_uri":"http://guilder.local/modulo1","method":"GET"} []
[2017-09-25 01:58:15] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2017-09-25 01:58:15] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "The controller for URI "/modulo1" is not callable. Expected method "indexAction" on class "AppBundle\Controller\ModuloController". Available methods: "modulo1Action", "modulo2Action", "modulo3Action", "resultadosEncAction", "setContainer"." at C:\xampp\htdocs\Proyecto\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\Controller\ControllerResolver.php line 98 {"exception":"[object] (InvalidArgumentException(code: 0): The controller for URI \"/modulo1\" is not callable. Expected method \"indexAction\" on class \"AppBundle\\Controller\\ModuloController\". Available methods: \"modulo1Action\", \"modulo2Action\", \"modulo3Action\", \"resultadosEncAction\", \"setContainer\". at C:\\xampp\\htdocs\\Proyecto\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\Controller\\ControllerResolver.php:98)"} []
[2017-09-25 01:58:29] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST /Controller/EncuestaController.php" (from "http://guilder.local/app_dev.php/modulo3")" at C:\xampp\htdocs\Proyecto\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /Controller/EncuestaController.php\" (from \"http://guilder.local/app_dev.php/modulo3\") at C:\\xampp\\htdocs\\Proyecto\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\xampp\\htdocs\\Proyecto\\var\\cache\\prod\\appProdProjectContainerUrlMatcher.php:201)"} []
[2017-09-25 02:06:26] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST /Controller/manejadorEncuesta.php" (from "http://guilder.local/app_dev.php/modulo3")" at C:\xampp\htdocs\Proyecto\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /Controller/manejadorEncuesta.php\" (from \"http://guilder.local/app_dev.php/modulo3\") at C:\\xampp\\htdocs\\Proyecto\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\xampp\\htdocs\\Proyecto\\var\\cache\\prod\\appProdProjectContainerUrlMatcher.php:201)"} []
[2017-09-25 02:07:51] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST /modulo/resultadosEnc.php" (from "http://guilder.local/app_dev.php/modulo3")" at C:\xampp\htdocs\Proyecto\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /modulo/resultadosEnc.php\" (from \"http://guilder.local/app_dev.php/modulo3\") at C:\\xampp\\htdocs\\Proyecto\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\xampp\\htdocs\\Proyecto\\var\\cache\\prod\\appProdProjectContainerUrlMatcher.php:201)"} []
[2017-09-25 02:09:36] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST /resultadosEnc.php" (from "http://guilder.local/app_dev.php/modulo3")" at C:\xampp\htdocs\Proyecto\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /resultadosEnc.php\" (from \"http://guilder.local/app_dev.php/modulo3\") at C:\\xampp\\htdocs\\Proyecto\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\xampp\\htdocs\\Proyecto\\var\\cache\\prod\\appProdProjectContainerUrlMatcher.php:201)"} []
[2017-09-25 02:10:37] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST /resultadosEnc.php" (from "http://guilder.local/app_dev.php/modulo3")" at C:\xampp\htdocs\Proyecto\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /resultadosEnc.php\" (from \"http://guilder.local/app_dev.php/modulo3\") at C:\\xampp\\htdocs\\Proyecto\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\xampp\\htdocs\\Proyecto\\var\\cache\\prod\\appProdProjectContainerUrlMatcher.php:201)"} []
[2017-09-25 02:11:23] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST /Resources/views/modulo/resultadosEnc.php" (from "http://guilder.local/app_dev.php/modulo3")" at C:\xampp\htdocs\Proyecto\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /Resources/views/modulo/resultadosEnc.php\" (from \"http://guilder.local/app_dev.php/modulo3\") at C:\\xampp\\htdocs\\Proyecto\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\xampp\\htdocs\\Proyecto\\var\\cache\\prod\\appProdProjectContainerUrlMatcher.php:201)"} []
[2017-09-25 02:13:15] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST /Resources/views/modulo/resultadosEnc.php" (from "http://guilder.local/app_dev.php/modulo3")" at C:\xampp\htdocs\Proyecto\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /Resources/views/modulo/resultadosEnc.php\" (from \"http://guilder.local/app_dev.php/modulo3\") at C:\\xampp\\htdocs\\Proyecto\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\xampp\\htdocs\\Proyecto\\var\\cache\\prod\\appProdProjectContainerUrlMatcher.php:201)"} []
[2017-09-25 02:13:32] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST /app/Resources/views/modulo/resultadosEnc.php" (from "http://guilder.local/app_dev.php/modulo3")" at C:\xampp\htdocs\Proyecto\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /app/Resources/views/modulo/resultadosEnc.php\" (from \"http://guilder.local/app_dev.php/modulo3\") at C:\\xampp\\htdocs\\Proyecto\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\xampp\\htdocs\\Proyecto\\var\\cache\\prod\\appProdProjectContainerUrlMatcher.php:201)"} []
[2017-09-25 02:14:30] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "POST /app/Resources/views/modulo/resultadosEnc.php" (from "http://guilder.local/app_dev.php/modulo3")" at C:\xampp\htdocs\Proyecto\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 125 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"POST /app/Resources/views/modulo/resultadosEnc.php\" (from \"http://guilder.local/app_dev.php/modulo3\") at C:\\xampp\\htdocs\\Proyecto\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:125, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0):  at C:\\xampp\\htdocs\\Proyecto\\var\\cache\\prod\\appProdProjectContainerUrlMatcher.php:201)"} []
